version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - python
      - from Blog import db
      - db.create_all()

artifacts:
  files:
    - '**/*'
